AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  go-sam-al2023
  
  Sample SAM Template for go-sam-al2023

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    CodeUri: app/
    Handler: bootstrap
    Runtime: provided.al2023
    Architectures: 
      - arm64
    

Resources:
  Foo:
      Type: AWS::Serverless::Function
      Properties:
        Events:
          CatchAll:
            Type: Api
            Properties:
              Path: /foo
              Method: GET
      Metadata:
        BuildMethod: makefile
  Bar:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /bar
            Method: GET    


Outputs:
  FooAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/foo/"
  Foo:
    Description: "First Lambda Function ARN"
    Value: !GetAtt Foo.Arn
  FooIamRole:
    Description: "Implicit IAM Role created for Foo function"
    Value: !GetAtt FooIamRole.Arn
